name: Run Makefile

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies (packages)
        run: |
          curl -LO https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus7/ldid_macosx_x86_64
          sudo install -m755 ldid_macosx_x86_64 /usr/local/bin/ldid
          brew install 7zip gnu-sed
          
      - name: Use Xcode 15.4
        run: |
          sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
          ./bump.sh

      - name: Compile palera1nLoader
        run: |
          make package PLATFORM=iphoneos PACKAGE_NAME=palera1nLoader

      - name: Compile palera1nLoaderTV
        run: |
          make package PLATFORM=appletvos PACKAGE_NAME=palera1nLoaderTV

